# GitHub Pages configuration
theme: jekyll-theme-minimal

# Custom headers
headers:
  - path: /*
    headers:
      - key: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com https://cdn.jsdelivr.net https://www.googletagmanager.com 'unsafe-inline'; style-src 'self' https://fonts.googleapis.com https://cdnjs.cloudflare.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com; frame-src 'self';"
      - key: X-Frame-Options
        value: "SAMEORIGIN"
      - key: X-Content-Type-Options
        value: "nosniff"
      - key: Referrer-Policy
        value: "strict-origin-when-cross-origin"
      - key: Permissions-Policy
        value: "camera=(), microphone=(), geolocation=()"
      - key: Strict-Transport-Security
        value: "max-age=31536000; includeSubDomains"
