# The URL the site will be built for
base_url = "https://abenstirling.com"
theme = "no-style-please"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]

[extra]
# Put all your custom variables here
favicon = "/images/logo.ico"
