baseURL = "https://abenstirling.github.io/"
title = "Ben Stirling"
paginate = 50
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false


[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Ben Stirling"
  description = "Ben Stirling"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Ben Stirling"
  images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    favicon = "/logo.ico"
    favicon16x16 = "/logo.ico"
    favicon32x32 = "/logo.ico"
    apple_touch_icon = "/logo.ico"
    safari_pinned_tab = "/logo.ico"

  [params.label]
    text = "Ben Stirling"
    icon = "https://avatars.githubusercontent.com/u/33791408?v=4"
    iconHeight = 35

  [params.homeInfoParams]
    Title = "Computer Engineer"
    Content = "Bots & Watts, Surfing & Turfing"



  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/abenstirling"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/abenstirling"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com/@abenstirling"
  



  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false

  

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]


#[[menu.main]]
#  identifier = "Engineering"
#  name = "Engineering"
#  url = "/categories/"
#  weight = 10


[[menu.main]]
  identifier = "resume"
 name = "Resume"
 url = "https://file.notion.so/f/s/0381ae1c-da24-475e-b06a-3db4b35100c0/Ben_Stirling_Resume_2023.pdf?id=aca32d40-7edf-46cf-9b42-c5fee9a840dd&table=block&spaceId=b27e04fa-bada-4c3d-9c7e-b368d46f2082&expirationTimestamp=1694304000000&signature=zm8diRcvQ-5suCzabZgO_5h_pz7Kh2YA3W1R3ZK_OQk&downloadName=Ben+Stirling+Resume+2023.pdf"
#  weight = 30

pygmentsUseClasses = true

[markup.highlight]
  noClasses = false
